server:
  port: 8080

spring:
  application:
    name: inventory-management-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: username
    password: 1
    hikari:
      connection-init-sql: select 1
      connection-test-query: select 1
      pool-name: inventory-management-service-pool
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

app:
  security:
    jwt:
      secret-key: lAyA3kvAGXvQfSWOw9y/HNx3af9KH0GElqItKbkIcAs=
      expiration: 86400000
      refresh-expiration: 604800000
    auth:
      white-list:
        - "/error"
        - "/auth/register"
        - "/h2-console/**"


logging:
  level:
    org.springframework.security: TRACE